### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by urherenow** [d0k3/GodMode9#15]
Am I missing an update for a lib or tool or perhaps because I'm on the bleeding edge ctrulib?

/devkitPro/devkitARM/projects/GodMode9/source/fatfs/ff.c: In function 'f_sync':
/devkitPro/devkitARM/projects/GodMode9/source/fatfs/ff.c:561:27: warning: unused variable 'lbuf' [-Wunused-variable]
 #define DEF_NAMBUF  WCHAR lbuf[_MAX_LFN+1];
                           ^
/devkitPro/devkitARM/projects/GodMode9/source/fatfs/ff.c:3677:2: note: in expansion of macro 'DEF_NAMBUF'
  DEF_NAMBUF
  ^

It builds/links just fine, but I don't want my own bugs added...

**Comment by d0k3** [comment]
You don't, that's a compiler warning from FATFS. I have the same warning. I'll leave that open until I fixed it.

**Comment by fox8091** [comment]
d0k3: Try compiling with -Wpedantic -Werror. :P

**Comment by urherenow** [comment]
@fox8091 that's a cop-out and doesn't fix the issue; only hides it. Hope you don't do stuff like that professionally...

**Comment by d0k3** [comment]
Fixed in https://github.com/d0k3/GodMode9/commit/2986ce3d5c45b5b4ab781d951bfdb30cb06018ec

**Comment by fox8091** [comment]
@urherenow No, that's perfection there. -Wpedantic turns on all even slight warnings in C, and -Werror makes every warning into a critical error. It lets you perfectly fix the code according to the ISO C standard.

**Comment by urherenow** [comment]
Ahhh, ok 👍
