### ISSUE TITLE
[BUG] CXI Files fail to build

### ISSUE THREAD

**Issue by kran27** [d0k3/GodMode9#727]
**So you want to report a bug?**
Hold on, there are ways you could make things easier for us:
* Give a clear description of the bug (what happened?).
When selecting the "Dump CXI/NDS file" certain games will fail to build, when one fails, it will always fail, and if it works, it always will. I have enough free space to dump the file.
* Give us clear steps to reproduce (when/how did it happen?).
See above
* Give us info about your system (where did it happen?).
When selecting the TMD file in the content folder of an installed app
* A photograph or even a short video of the bug happening is always helpful!

**Info about your system**
Include this info to make our work easier:
* Console type (O3DS/N3DS)
O3DS
* Anything special about your console? (defects, custom modifications,...)
no known defects or hardmods
* Bootloader (boot9strap/fastboot3ds)
fb3ds
* Did you chainload GodMode9 via Luma?
no
* Helpful hint: *if you followed the Guide, boot9strap is your bootloader and Luma is your chainloader.*

**Help yourself**
*Especially for any kind of boot issue ("GodMode9 doesn't boot")*, but also in many other cases these steps make a lot of sense and we will ask you to do them anyways:
* Check your SD card (using h2testw, f.e.) or try a different one (you wouldn't believe how common failing/fake SD cards are, and what kinds of bugs are caused by them).
* Switch to fastboot3DS using [https://github.com/d0k3/OpenFirmInstaller](OpenFirmInstaller).

**Have you actually read this?**
[x] I have read the information above

**Comment by kran27** [comment]
After a bit more testing, it appears to fail when the .tmd file is not in between the 2 .app files.

**Comment by d0k3** [comment]
Does building a CIA work in these cases? I may already have an idea how to fix this

**Comment by d0k3** [comment]
Okay, I tried to reproduce this, but with no success.

For the titles that don't work, can you dump the CXI via the title manager (find it in the HOME button menu)? Can you build a CIA for these titles? And can you find a small one not working, and maybe contact me on Discord, so we can work something out?

**Comment by kran27** [comment]
the title manager doesn't have an option to dump .cxi files, (other than browsing to the folder), and building a CIA does work. the smallest one that doesnt work is the official Super Metroid VC.

**Comment by kran27** [comment]
Hi, sorry for late response. This version gives the error "possible crypto error" on every game that suffers from this issue.

**Comment by d0k3** [comment]
Alright, sorry about the long radio silence. Can you tell me if it fails before the progress bar is shown or afterwards?

**Comment by d0k3** [comment]
We'll make this simpler - just try this test build:
[GodMode9_test_09102021.zip](https://github.com/d0k3/GodMode9/files/7315471/GodMode9_test_09102021.zip)

Do you get an additional prompt for titles that fail?

**Comment by d0k3** [comment]
@kran27 - don't want to bug you, but did you get this solved in the meantime? Tried the test build? Any updates?

**Comment by kran27** [comment]
totally missed your other message, just tried that build, no other message, still fails.

**Comment by d0k3** [comment]
Alright, thanks for getting back. You don't get any prompt now, so this is not a crypto error. We can also exclude lot's of other problems, cause CIA building works in the places CXI doesn't.

There's only one source of error left, and that's file operations (open, read, seek). The most likely cause is some problem with your SD card. Can you try another SD (that would be the best option) or at least check the one you got thoroughly (complete surface scan with chkdsk, or h2testw).

**Comment by d0k3** [comment]
Alright, we hadn't had any updates on this in a long time, so I'm assuming this was an SD card issue and is already fixed. @kran27 - feel free to get back if the issue still persists.
